name: Validate MPM Downloads
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.



on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: [
          'R2025aU0',
          'R2024bU6',
          'R2024bU5',
          # 'R2024bU4',
          # 'R2024bU3',
          # 'R2024bU2',
          # 'R2024bU1',
          # 'R2024bU0',
          # 'R2024aU7',
          # 'R2024aU6',
          # 'R2024aU5',
          # 'R2024aU4',
          # 'R2024aU3',
          # 'R2024aU2',
          # 'R2024aU1',
          # 'R2024aU0',
          # 'R2023bU9',
          # 'R2023bU8',
          # 'R2023bU7',
          # 'R2023bU6',
          # 'R2023bU5',
          # 'R2023bU4',
          # 'R2023bU3',
          # 'R2023bU2',
          # 'R2023bU10',
          # 'R2023bU1',
          # 'R2023bU0',
          # 'R2023aU8',
          # 'R2023aU7',
          # 'R2023aU6',
          # 'R2023aU5',
          # 'R2023aU4',
          # 'R2023aU3',
          # 'R2023aU2',
          # 'R2023aU1',
          # 'R2023aU0',
          # 'R2022bU9',
          # 'R2022bU8',
          # 'R2022bU7',
          # 'R2022bU6',
          # 'R2022bU5',
          # 'R2022bU4',
          # 'R2022bU3',
          # 'R2022bU2',
          # 'R2022bU10',
          # 'R2022bU1',
          # 'R2022bU0'
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run download and check script
        run: |
          chmod +x download-and-check.sh
          ./download-and-check.sh ${{ matrix.release }}